name: "Simplecov Report"
description: "Simplecov Report"
author: aki77
branding:
  icon: check-square
  color: green
inputs:
  failedThreshold:
    description: Failed threshold
    default: "90"
    required: false
  resultPath:
    description: "json path"
    default: "coverage/.last_run.json"
    required: false
  token:
    description: "Github token"
    required: true
  pullRequestId:
    description: "Pull Request ID. Useful when running this action triggered by another workflow (e.g. when using `workflow_dispatch`)."
    required: false
  customTitle:
    description: 'Custom title'
    required: false
  customText:
    description: 'Custom text'
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
